name: CI Pipeline         # nombre visible en la pestana de Actions

on:                       # eventos que dispara el workflow
  push:                   # cuando se hace push a la rama main de github
    branches: [ main ]    # ...a la rama main
  
  pull_request:           # cuando alguien hace pull request(pr) a la rama main
    branches: [ main ]    # ...a la rama main

  workflow_dispatch:      # permite ejecutar el workflow manualmente desde la pestaña Actions o UI

jobs:                     # define los jobs que se ejecutaran en el workflow
  run-test:                           # nombre del job
    name: Run Tests                   # nombre visible del job
    runs-on: ubuntu-latest            # tipo de runner, define el sistema operativo donde se ejecutara el job

    steps:                            # define los pasos que se ejecutaran en el job, pasos en orden secuencial
      - name: Checkout Code           # nombre visible del paso
        uses: actions/checkout@v3     # acción que hace checkout del código fuente del repositorio, clona el repo en el runner

      - name: Setup Node.js
        uses: actions/setup-node@v3   # instala Node.js en el runner
        with:
          node-version: '20'          # versión de Node.js a instalar
      
      - name: Install Dependencies    # instalar dependencias del proyecto
        run: npm ci                   # comando para instalar dependencias usando npm

      - name: Run Tests               # ejecutar pruebas unitarias
        run: npm test                 # comando para ejecutar pruebas unitarias usando npm