name: CI Pipeline Completo

on:                       # eventos que dispara el workflow
  push:                   # cuando se hace push a la rama main de github
    branches: [ main ]    # ...a la rama main
  
  pull_request:           # cuando alguien hace pull request(pr) a la rama main
    branches: [ main ]    # ...a la rama main

  workflow_dispatch:      # permite ejecutar el workflow manualmente desde la pestaña Actions o UI

jobs:                     

  test:
    name: Test matrix Node ${{matrix.node-version}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22] # versiones de node a testear
      fail-fast: false # si un job falla, no detiene los demás

      steps:
        - uses: actions/checkout@v4
        - name: Setup Node Js ${{matrix.node-version}}
          uses: actions/setup-node@v4
          with:
            node-version: ${{matrix.node-version}}
            cache: 'npm'
        - run: npm ci
        - run: npm test