name: CI Pipeline Completo

on:                       # eventos que dispara el workflow
  push:                   # cuando se hace push a la rama main de github
    branches: [ main ]    # ...a la rama main
  
  pull_request:           # cuando alguien hace pull request(pr) a la rama main
    branches: [ main ]    # ...a la rama main

  workflow_dispatch:      # permite ejecutar el workflow manualmente desde la pestaña Actions o UI

# Variables a nivel del workflow
env: 
  NODE_VERSION: "20"

jobs:                     

  build:                  # nombre del job
    name: Build
    runs-on: ubuntu-latest # sistema operativo donde se ejecutará el job

    steps:                # pasos a ejecutar en el job
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - run: npm ci
      - name: Build app
        run: npm run build
        env:
          APP_VERSION: ${{ vars.APP_VERSION || '1.0.0' }} # variable de entorno para la versión de la app

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{github.sha}}
          path: dist/
          retention-days: 7
