name: CI Pipeline Completo

on:                       # eventos que dispara el workflow
  push:                   # cuando se hace push a la rama main de github
    branches: [ main ]    # ...a la rama main
  
  pull_request:           # cuando alguien hace pull request(pr) a la rama main
    branches: [ main ]    # ...a la rama main

  workflow_dispatch:      # permite ejecutar el workflow manualmente desde la pestaña Actions o UI

# Variables a nivel del workflow
env: 
  NODE_VERSION: "20"

jobs:                     

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm ci
      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage-{{github.sha}}
          path: coverage/
          retention-days: 7